### ISSUE TITLE
Generator ask if I want Mongo, I do not, but generator still gives me pieces of Mongo

### ISSUE THREAD

**Issue by maartenraes** [digipolisantwerp/starter-kit-ui_app_nodejs#49]
de gegenereerde docker-compose.yml toch een dependency op een mongoDB, dit terwijl ik in de wizard gekozen heb dat ik geen database nodig heb.

```
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:3.6.2
    ports:
      - "27017:27017" 
```
